In [4]:
import os
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="4"

In [1]:
#!pip install theano
import pandas as pd
import numpy as np

In [2]:
data1 = pd.read_csv('./data_RNA_Seq_v2_mRNA_median_all_sample_Zscores.txt', sep='\t')
data2 = pd.read_csv('./data_bcr_clinical_data_patient.txt', sep='\t')
data1 = data1.set_index('Hugo_Symbol', drop = True)

In [3]:
data1 = data1.T
data1.rename(index = lambda x : str(x).replace('-01', ''), inplace = True)
data1 = data1.iloc[1:]
data1

Hugo_Symbol,LOC100130426,UBE2Q2P3,UBE2Q2P3,HMGB1P1,TIMM23,MOXD2,LOC155060,RNU12-2P,SSX9,LOC317712,...,LEPROTL1,LEPROT,LEPR,LEP,LETM1,LETM2,LETMD1,LEUTX,LFNG,LGALS12
TCGA-05-4244,-2.2883,0.0380,0.0691,-1.9057,-0.0395,NaN,1.0624,0.5387,-1.2501,NaN,...,-0.9598,0.8191,-0.2769,-1.2250,-0.3300,-0.9989,-0.6894,-1.6334,1.0425,0.4468
TCGA-05-4249,-2.2883,-0.3514,0.1971,-0.2950,0.1945,NaN,-0.0690,1.4599,-1.2501,NaN,...,0.6565,0.5753,0.2925,1.5104,-0.7330,-0.3781,-1.0871,-1.6334,0.6832,-0.2605
TCGA-05-4250,-2.2883,-0.3435,-0.7239,-1.9091,0.7761,NaN,-1.4074,-2.1796,-1.2501,NaN,...,1.7623,0.7415,-0.8597,-0.8899,-0.4638,1.1186,-1.0109,-1.6334,0.0579,-0.5658
TCGA-05-4382,-2.2883,0.1873,-0.4402,-0.5333,-0.1787,NaN,0.5870,-0.6958,-0.9868,NaN,...,0.1698,0.7991,-0.0641,1.3887,0.4908,0.0490,0.0262,-1.6334,1.1943,-0.2502
TCGA-05-4384,-2.2883,-1.2251,-1.3555,-0.8895,-1.1778,NaN,0.7614,-0.3706,-1.2501,NaN,...,-0.2033,0.4580,0.4896,1.8020,-0.0446,-0.7013,0.7738,-1.6334,1.5428,-0.3712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-NJ-A55O,-2.2883,0.5729,1.0176,-0.0218,0.0408,NaN,0.6719,0.7543,-1.2501,NaN,...,0.0428,0.1880,-0.2000,2.4699,0.4276,-0.1761,0.6492,-1.6334,-0.0989,NaN
TCGA-NJ-A55R,-2.2883,-0.1679,-0.0462,-0.8099,-0.3206,NaN,1.1540,-0.1200,-1.2501,NaN,...,0.0277,-0.2969,-0.3690,0.2701,1.6736,-1.1747,1.2036,-1.6334,1.1606,NaN
TCGA-NJ-A7XG,-2.2883,1.8645,2.7613,-0.4522,-0.6611,NaN,1.0220,-2.1796,-1.2501,NaN,...,0.2419,-0.8356,-0.5262,-1.4815,-0.4239,1.4361,0.6937,-1.6334,-0.7499,NaN
TCGA-O1-A52J,-2.2883,0.4532,1.0870,-1.3473,0.7679,NaN,0.1428,2.9555,-1.2501,NaN,...,-0.4844,-0.2131,0.2455,-1.1465,-0.9973,0.0914,0.1271,-1.6334,-1.2617,NaN
TCGA-S2-AA1A,-2.2883,0.9225,-0.2293,-0.7319,-1.1610,NaN,1.1789,-0.2677,-1.2501,NaN,...,0.3192,0.1646,-0.3715,-1.4815,-1.3599,0.2304,0.1927,-1.6334,0.4763,NaN

In [4]:
data2 = data2.iloc[4:]
data2 = data2[['Patient Identifier', 'Overall Survival Status', 'Overall Survival (Months)']]
data2 = data2.set_index('Patient Identifier', drop = True)
data2

                   Overall Survival Status Overall Survival (Months)
Patient Identifier
TCGA-05-4244                      0:LIVING                         0
TCGA-05-4245                      0:LIVING                     23.98
TCGA-05-4249                      0:LIVING                     50.03
TCGA-05-4250                    1:DECEASED                      3.98
TCGA-05-4382                      0:LIVING                     19.94
...                                    ...                       ...
TCGA-NJ-A55O                      0:LIVING                      0.43
TCGA-NJ-A55R                      0:LIVING                     19.81
TCGA-NJ-A7XG                      0:LIVING                     20.27
TCGA-O1-A52J                    1:DECEASED                     59.07
TCGA-S2-AA1A                      0:LIVING                     16.85

[522 rows x 2 columns]

In [5]:
data = data2.merge(data1, left_on = 'Patient Identifier', right_index = True)

In [6]:
missing_data = data.isnull().sum() / len(data) > 0.8

missing_data = missing_data.to_frame()
missing_data.loc[missing_data[0] == True]

               0
MOXD2       True
LOC317712   True
SPATA31B1P  True
REXO1L6P    True
PPBPL1      True
...          ...
KRTAP6-2    True
LCE1D       True
LCE3B       True
LCE3C       True
LCE4A       True

[62 rows x 1 columns]

In [7]:
missing_data_index = missing_data.loc[missing_data[0] == True, :].index
data = data.drop(missing_data_index, axis = 1)
data

,Overall Survival Status,Overall Survival (Months),LOC100130426,UBE2Q2P3,UBE2Q2P3,HMGB1P1,TIMM23,LOC155060,RNU12-2P,SSX9,...,LEPROTL1,LEPROT,LEPR,LEP,LETM1,LETM2,LETMD1,LEUTX,LFNG,LGALS12
Patient Identifier,,,,,,,,,,,,,,,,,,,,,
TCGA-05-4244,0:LIVING,0,-2.2883,0.0380,0.0691,-1.9057,-0.0395,1.0624,0.5387,-1.2501,...,-0.9598,0.8191,-0.2769,-1.2250,-0.3300,-0.9989,-0.6894,-1.6334,1.0425,0.4468
TCGA-05-4249,0:LIVING,50.03,-2.2883,-0.3514,0.1971,-0.2950,0.1945,-0.0690,1.4599,-1.2501,...,0.6565,0.5753,0.2925,1.5104,-0.7330,-0.3781,-1.0871,-1.6334,0.6832,-0.2605
TCGA-05-4250,1:DECEASED,3.98,-2.2883,-0.3435,-0.7239,-1.9091,0.7761,-1.4074,-2.1796,-1.2501,...,1.7623,0.7415,-0.8597,-0.8899,-0.4638,1.1186,-1.0109,-1.6334,0.0579,-0.5658
TCGA-05-4382,0:LIVING,19.94,-2.2883,0.1873,-0.4402,-0.5333,-0.1787,0.5870,-0.6958,-0.9868,...,0.1698,0.7991,-0.0641,1.3887,0.4908,0.0490,0.0262,-1.6334,1.1943,-0.2502
TCGA-05-4384,0:LIVING,13.99,-2.2883,-1.2251,-1.3555,-0.8895,-1.1778,0.7614,-0.3706,-1.2501,...,-0.2033,0.4580,0.4896,1.8020,-0.0446,-0.7013,0.7738,-1.6334,1.5428,-0.3712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-NJ-A55O,0:LIVING,0.43,-2.2883,0.5729,1.0176,-0.0218,0.0408,0.6719,0.7543,-1.2501,...,0.0428,0.1880,-0.2000,2.4699,0.4276,-0.1761,0.6492,-1.6334,-0.0989,NaN
TCGA-NJ-A55R,0:LIVING,19.81,-2.2883,-0.1679,-0.0462,-0.8099,-0.3206,1.1540,-0.1200,-1.2501,...,0.0277,-0.2969,-0.3690,0.2701,1.6736,-1.1747,1.2036,-1.6334,1.1606,NaN
TCGA-NJ-A7XG,0:LIVING,20.27,-2.2883,1.8645,2.7613,-0.4522,-0.6611,1.0220,-2.1796,-1.2501,...,0.2419,-0.8356,-0.5262,-1.4815,-0.4239,1.4361,0.6937,-1.6334,-0.7499,NaN
TCGA-O1-A52J,1:DECEASED,59.07,-2.2883,0.4532,1.0870,-1.3473,0.7679,0.1428,2.9555,-1.2501,...,-0.4844,-0.2131,0.2455,-1.1465,-0.9973,0.0914,0.1271,-1.6334,-1.2617,NaN
TCGA-S2-AA1A,0:LIVING,16.85,-2.2883,0.9225,-0.2293,-0.7319,-1.1610,1.1789,-0.2677,-1.2501,...,0.3192,0.1646,-0.3715,-1.4815,-1.3599,0.2304,0.1927,-1.6334,0.4763,NaN

In [8]:
dup_cols = data.columns[data.columns.duplicated()]
dup_indices = [ [i, col] for i, col in enumerate(data.columns) if col in dup_cols]
print(dup_indices)
dup_indices.sort(key=lambda x:x[1])
dup_indices = list(list(zip(*dup_indices))[0])
indexes = []
for i in range(0, len(dup_indices), 2):
    pair = data.iloc[:, dup_indices[i:i+2]]
    variances = pair.var()   
    if variances.iloc[0] < variances.iloc[1]:
        indexes.append(dup_indices[i])        
    else:
        indexes.append(dup_indices[i+1])
print(indexes)
data = data.iloc[:, [i for i in range(data.shape[1]) if i not in indexes]]
print(data)

[[3, 'UBE2Q2P3'], [4, 'UBE2Q2P3'], [1691, 'CC2D2B'], [1715, 'CCDC7'], [2252, 'C1orf84'], [3050, 'CC2D2B'], [3179, 'CCDC7'], [4605, 'CYorf15B'], [4606, 'CYorf15B'], [8898, 'C1orf84']]
[2252, 3050, 3179, 4606, 4]
                   Overall Survival Status Overall Survival (Months)  \
Patient Identifier
TCGA-05-4244                      0:LIVING                         0
TCGA-05-4249                      0:LIVING                     50.03
TCGA-05-4250                    1:DECEASED                      3.98
TCGA-05-4382                      0:LIVING                     19.94
TCGA-05-4384                      0:LIVING                     13.99
...                                    ...                       ...
TCGA-NJ-A55O                      0:LIVING                      0.43
TCGA-NJ-A55R                      0:LIVING                     19.81
TCGA-NJ-A7XG                      0:LIVING                     20.27
TCGA-O1-A52J                    1:DECEASED                     59.07
TCGA-S2-AA1A                      0:LIVING                     16.85

                    LOC100130426  UBE2Q2P3  HMGB1P1  TIMM23  LOC155060  \
Patient Identifier
TCGA-05-4244             -2.2883    0.0380  -1.9057 -0.0395     1.0624
TCGA-05-4249             -2.2883   -0.3514  -0.2950  0.1945    -0.0690
TCGA-05-4250             -2.2883   -0.3435  -1.9091  0.7761    -1.4074
TCGA-05-4382             -2.2883    0.1873  -0.5333 -0.1787     0.5870
TCGA-05-4384             -2.2883   -1.2251  -0.8895 -1.1778     0.7614
...                          ...       ...      ...     ...        ...
TCGA-NJ-A55O             -2.2883    0.5729  -0.0218  0.0408     0.6719
TCGA-NJ-A55R             -2.2883   -0.1679  -0.8099 -0.3206     1.1540
TCGA-NJ-A7XG             -2.2883    1.8645  -0.4522 -0.6611     1.0220
TCGA-O1-A52J             -2.2883    0.4532  -1.3473  0.7679     0.1428
TCGA-S2-AA1A             -2.2883    0.9225  -0.7319 -1.1610     1.1789

                    RNU12-2P    SSX9   EZHIP  ...  LEPROTL1  LEPROT    LEPR  \
Patient Identifier                            ...
TCGA-05-4244          0.5387 -1.2501 -0.9569  ...   -0.9598  0.8191 -0.2769
TCGA-05-4249          1.4599 -1.2501 -0.9569  ...    0.6565  0.5753  0.2925
TCGA-05-4250         -2.1796 -1.2501 -0.9569  ...    1.7623  0.7415 -0.8597
TCGA-05-4382         -0.6958 -0.9868  1.1884  ...    0.1698  0.7991 -0.0641
TCGA-05-4384         -0.3706 -1.2501 -0.9569  ...   -0.2033  0.4580  0.4896
...                      ...     ...     ...  ...       ...     ...     ...
TCGA-NJ-A55O          0.7543 -1.2501 -0.9569  ...    0.0428  0.1880 -0.2000
TCGA-NJ-A55R         -0.1200 -1.2501  0.1089  ...    0.0277 -0.2969 -0.3690
TCGA-NJ-A7XG         -2.1796 -1.2501 -0.9569  ...    0.2419 -0.8356 -0.5262
TCGA-O1-A52J          2.9555 -1.2501  0.5042  ...   -0.4844 -0.2131  0.2455
TCGA-S2-AA1A         -0.2677 -1.2501  0.3220  ...    0.3192  0.1646 -0.3715

                       LEP   LETM1   LETM2  LETMD1   LEUTX    LFNG  LGALS12
Patient Identifier
TCGA-05-4244       -1.2250 -0.3300 -0.9989 -0.6894 -1.6334  1.0425   0.4468
TCGA-05-4249        1.5104 -0.7330 -0.3781 -1.0871 -1.6334  0.6832  -0.2605
TCGA-05-4250       -0.8899 -0.4638  1.1186 -1.0109 -1.6334  0.0579  -0.5658
TCGA-05-4382        1.3887  0.4908  0.0490  0.0262 -1.6334  1.1943  -0.2502
TCGA-05-4384        1.8020 -0.0446 -0.7013  0.7738 -1.6334  1.5428  -0.3712
...                    ...     ...     ...     ...     ...     ...      ...
TCGA-NJ-A55O        2.4699  0.4276 -0.1761  0.6492 -1.6334 -0.0989      NaN
TCGA-NJ-A55R        0.2701  1.6736 -1.1747  1.2036 -1.6334  1.1606      NaN
TCGA-NJ-A7XG       -1.4815 -0.4239  1.4361  0.6937 -1.6334 -0.7499      NaN
TCGA-O1-A52J       -1.1465 -0.9973  0.0914  0.1271 -1.6334 -1.2617      NaN
TCGA-S2-AA1A       -1.4815 -1.3599  0.2304  0.1927 -1.6334  0.4763      NaN

[515 rows x 9458 columns]

In [9]:
data['Overall Survival Status'] = data['Overall Survival Status'].replace({'1:DECEASED': 1, '0:LIVING': 0})
data = data.rename(columns={'Overall Survival (Months)': 't', 'Overall Survival Status': 'e'})
data['t'] = data['t'].replace({'[Not Available]': 0})
from sklearn.model_selection import train_test_split
train, test = train_test_split(data, test_size=0.2, random_state=42)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [10]:
train = train.reset_index()
test = test.reset_index()
t_train = train['t'].to_numpy(dtype='float')
e_train = train['e']
t_test = test['t'].to_numpy(dtype='float')
e_test = test['e']
train = train.drop(['e','t','Patient Identifier'],axis=1)
test = test.drop(['e','t','Patient Identifier'],axis=1)
X_train = train.to_numpy(dtype=float)
X_test = train.to_numpy(dtype=float)

In [11]:
#model_params = dict(node_map = None, input_split = None)
#search_params = dict(method = "nesterov", learning_rate=0.01, momentum=0.9,
#   max_iter=2000, stop_threshold=0.995, patience=1000, patience_incr=2, rand_seed = 123,
#    eval_step=23, lr_decay = 0.9, lr_growth = 1.0)
#cv_params = dict(cv_seed=1, n_folds=5, cv_metric = "loglikelihood",
#    L2_range = numpy.arange(-4.5,1,0.5))

In [13]:
!git clone https://github.com/PathologyDataScience/SurvivalNet.git

Cloning into 'SurvivalNet'...
remote: Enumerating objects: 2829, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 2829 (delta 2), reused 0 (delta 0), pack-reused 2823
Receiving objects: 100% (2829/2829), 204.83 MiB | 40.47 MiB/s, done.
Resolving deltas: 100% (991/991), done.

In [3]:
!git push

Username for 'https://github.com': ^C